name: Generate snake animation

on:
  schedule: # Executes at 12 AM and 12 PM every day
    - cron: "0 */12 * * *"

  workflow_dispatch: # Allows manual trigger from GitHub UI

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write  # Allows the workflow to push to the output branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Kittu-Priya
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
